name: automatic_spring_animation
description: this package animates widgets with springs when their location changes
version: 0.0.1-dev.1
repository: https://github.com/kobutri/automatic_spring_animation.git

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

